<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-GDISGSQ" name="Practice_TestNg.CheckDashBoard_Officer_TestNg" tests="4" failures="1" timestamp="2023-01-12T17:59:50 IST" time="60.972" errors="0">
  <testcase name="checkdashboard_officer" time="2.662" classname="Practice_TestNg.CheckDashBoard_Officer_TestNg">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at Practice_TestNg.CheckDashBoard_Officer_TestNg.checkdashboard_officer(CheckDashBoard_Officer_TestNg.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkdashboard_officer -->
  <system-out>
    <![CDATA[checkdashboard_officer========>Testscripts execution started 
===Testscript Execution fail=======]]>
  </system-out>
  <testcase name="checkdashboard_Bf_create_officer" time="21.893" classname="Practice_TestNg.CheckDashBoard_Officer_TestNg"/>
  <system-out>
    <![CDATA[checkdashboard_Bf_create_officer========>Testscripts execution started 
checkdashboard_Bf_create_officer=======>Testscript excute successfully]]>
  </system-out>
  <testcase name="create_Emp_Officer" time="34.488" classname="Practice_TestNg.CheckDashBoard_Officer_TestNg"/>
  <system-out>
    <![CDATA[create_Emp_Officer========>Testscripts execution started 
create_Emp_Officer=======>Testscript excute successfully]]>
  </system-out>
  <testcase name="checkdashboard_Af_create_officer" time="1.929" classname="Practice_TestNg.CheckDashBoard_Officer_TestNg"/>
  <system-out>
    <![CDATA[checkdashboard_Af_create_officer========>Testscripts execution started 
checkdashboard_Af_create_officer=======>Testscript excute successfully]]>
  </system-out>
</testsuite> <!-- Practice_TestNg.CheckDashBoard_Officer_TestNg -->
