<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-GDISGSQ" name="Practice_TestNg.CheckDashBoard_Assistant_TestNg" tests="4" failures="1" timestamp="2023-01-12T17:56:55 IST" time="65.541" errors="0">
  <testcase name="checkDashboard_Assistant" time="21.501" classname="Practice_TestNg.CheckDashBoard_Assistant_TestNg">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at Practice_TestNg.CheckDashBoard_Assistant_TestNg.checkDashboard_Assistant(CheckDashBoard_Assistant_TestNg.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkDashboard_Assistant -->
  <system-out>
    <![CDATA[checkDashboard_Assistant========>Testscripts execution started 
===Testscript Execution fail=======]]>
  </system-out>
  <testcase name="checkDashBoard_Bf_Create_emp_Assistant" time="1.749" classname="Practice_TestNg.CheckDashBoard_Assistant_TestNg"/>
  <system-out>
    <![CDATA[checkDashBoard_Bf_Create_emp_Assistant========>Testscripts execution started 
checkDashBoard_Bf_Create_emp_Assistant=======>Testscript excute successfully]]>
  </system-out>
  <testcase name="create_emp_Assistant" time="40.399" classname="Practice_TestNg.CheckDashBoard_Assistant_TestNg"/>
  <system-out>
    <![CDATA[create_emp_Assistant========>Testscripts execution started 
create_emp_Assistant=======>Testscript excute successfully]]>
  </system-out>
  <testcase name="checkDashBoard_Af_Create_emp_Assistant" time="1.892" classname="Practice_TestNg.CheckDashBoard_Assistant_TestNg"/>
  <system-out>
    <![CDATA[checkDashBoard_Af_Create_emp_Assistant========>Testscripts execution started 
checkDashBoard_Af_Create_emp_Assistant=======>Testscript excute successfully]]>
  </system-out>
</testsuite> <!-- Practice_TestNg.CheckDashBoard_Assistant_TestNg -->
